name: E2E Tests
on:
  workflow_call:
    inputs:
        ref:
          type: string
          default: ${{ github.ref }}
        app_id:
          description: GitHub App ID for Auth (or client ID)
          type: string
          required: true
    secrets:
        app_secret:
          description: GitHub App client secret for Auth
          required: true
jobs:
  e2e-tests:
    name: Test
    runs-on: ubuntu-latest
    env:
      CYPRESS_RESPONSE_TIMEOUT: 200000
      CYPRESS_DEFAULT_COMMAND_TIMEOUT: 30000
      CYPRESS_RETRIES: 2
    strategy:
      # fail-fast: true
      matrix:
        include:
          - branch: develop
            webpack: dev
          - branch: master
            webpack: update
    steps:
        - uses: actions/checkout@v4
          with:
            path: ab_platform_pwa
            submodules: true
            ref: ${{ inputs.ref }}
            repositories: ab_service_web
        - uses: actions/checkout@v4
          with:
            path: web
            repository: digi-serve/ab_service_web
            token: ${{ secrets.GITHUB_TOKEN }}
            ref: ${{ matrix.branch }}

        - run: npm i
          working-directory: ./ab_platform_pwa

        - name: Webpack
          run: npm run build:${{ matrix.webpack }}
          working-directory: ./ab_platform_pwa

        # webpack expects the folder to be called "web" ab-install action expects "ab_service_web"
        - run: mv web ab_service_web

        - uses: digi-serve/ab-install-action@v1
          with:
            port: 8080
            folder: ab
            repository: digi-serve/ab_service_web

        - name: Check out kitchen-sink tests
          uses: actions/checkout@v4
          with:
            repository: digi-serve/kitchensink_app
            path: ab/test/e2e/cypress/e2e/kitchensink_app

        # These next steps are to save our ablogs to file
        - run: npm install pm2@latest -g
        - name: Save Logs
          run: pm2 start ./logs.js -- --toFile logs/ABServices.log
          working-directory: ./ab

        # Skipping the wait step. Cypress has a bit of wait time built in.
        # Run test
        - name: Run Cypress Tests
          run: npm run test:e2e:app -- --browser chrome
          working-directory: ./ab

        - uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: cypress-screenshots
            path: ./ab/test/e2e/cypress/screenshots

        - uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: ABServices.log
            path: ./ab/logs/ABServices.log
